### ISSUE TITLE
Mod IPEX1 antennas for BCM943602CDP

### ISSUE THREAD

**Issue by ghost** [sarkrui/NUC8i7BEH#12]
Wifi and bluetooth are working, but the reception is very bad.

I wasn't able to connect the existing antenna to the BCM943602CDP due to connector size difference. Did you use adaptors or add external antennas?

**Comment by sarkrui** [comment]
Hi @jacealot, 
I used to have the same issue. The original antennas on NUC are using IPEX4 connector while the BCM943602CDP is using IPEX1. Thus, I completely removed the original ones and replaced them with four IPEX1. However, it's worth mentioning that the quality of the signals (for both Wi-Fi and Bluetooth are NOT as well as the original ones. 
![](https://i.imgur.com/fq0mLkk.jpg)
