### ISSUE TITLE
Bluetooth not detected using BCM94360CS2(only WiFi works)

### ISSUE THREAD

**Issue by nash886** [sarkrui/NUC8i7BEH#13]
Followed your guide line by line. Everything works except for bluetooth. I'm using BCM94360 WiFi/Bluetooth card. Same card works when i swap OS with ubuntu where bluetooth is detected and works fine so rules out any hardware related issue.

Running out of ideas and **Need Help**!

Attaching my [config plist](https://www.dropbox.com/s/6l61npw5iws8j2y/config.plist?dl=0) and [IORegistry](https://www.dropbox.com/s/mjq8zlk092vlex0/NUC%E2%80%99s%20Mac%20mini.ioreg?dl=0) file if that helps

![Screen Shot 2019-09-29 at 3 26 54 PM](https://user-images.githubusercontent.com/55066688/65838125-edf5e900-e2cd-11e9-8bed-395655888427.png)
![Screen Shot 2019-09-29 at 3 37 58 PM](https://user-images.githubusercontent.com/55066688/65838244-2f3ac880-e2cf-11e9-92d1-d70b1d366174.png)
![Screen Shot 2019-09-29 at 2 45 12 PM](https://user-images.githubusercontent.com/55066688/65838246-31048c00-e2cf-11e9-9577-23821603717a.png)

**Comment by sarkrui** [comment]
Hi @nash886 ,

I guess it might be something wrong with your USB limits although there's `USBInjectAll.kext` in the EFI (or is it?). You could try using [USB port on the release page](https://github.com/sarkrui/NUC8i7BEH-Hackintosh-Build/releases). Remember to remove the USBInjectAll one if you're using the NUC8 USBPort.kext, Repair permissions and rebuild cache. 

You could also try restoring `NVRAM` by pressing `F11` at the Clover Bootup page where you have serval bootable volumes to choose. Hope this wizard work for you! Good luck.

**Comment by nash886** [comment]
@sarkrui 

It was the USBInjectAll. Replacing one with in this repo resolved this issue. Everything works now(airdrop/iMessage..etc).

Thanks again so much.
