### ISSUE TITLE
NUC8i5BEH user for help,about egpu can not driver.😥

### ISSUE THREAD

**Issue by justwezzz** [sarkrui/NUC8i7BEH#16]
hi,@sarkrui,I know it's NUC8i7BEH's repository,but I really can't find answer anywhere even omnipotent TaoBao.So you are my last hope.🥺

I have 
1. NUC8i **5** BEH
2. [Mantiz eGPU](https://zhuanlan.zhihu.com/p/40113704)
3. rx580 8g 2304sp

I can running it in window10 1903,it works fine.

but in macos(10.14.6) use egpu,boot progress bar end , I got a blank screen,it can't enter to macos.

this log is the last info before blank screen
![2D08E618858D99033A6C6932663C72BB](https://user-images.githubusercontent.com/1901634/66543886-32ed0b80-eb69-11e9-8597-0298f8b8eb96.JPG)

can you help me?🥺

**Comment by sarkrui** [comment]
You should probably try injecting a *headless* `ig-platform-id` for the iGPU, which would disable the video output from the onboard HDMI (and type-c). For more practical information, check this issue #4 How to get eGPU HW acceleration in Final Cut Pro X.

**Comment by justwezzz** [comment]
@sarkrui thank you for your reply，I will try tonight😀

**Comment by justwezzz** [comment]
hi @sarkrui , I add framebuffer-portcount to config file , but still blank screen.
I found a strange thing,after I add framebuffer-portcount=0 to config file,it should disabled my HDMI port,but I can still use it,seems the config not work for me.
<img width="642" alt="QQ20191010-212742@2x" src="https://user-images.githubusercontent.com/1901634/66573681-a90f6380-eba5-11e9-9703-676c28e73557.png">

**Comment by sarkrui** [comment]
You seemed not using my EFI.
