### ISSUE TITLE
Thunderbolt instructions

### ISSUE THREAD

**Issue by BumpyClock** [sarkrui/NUC8i7BEH#2]
Any chance you could detail what you did to get thunderbolt working?

I have Thunderbolt security set to legacy. My sonnet box powers on but my Vega 56 does not get detected. I am Bios 0081 though, tried downgrading but couldn't.

**Comment by sarkrui** [comment]
As I mentioned in the `Not Working` section, AFAIK, Thunderbolt 3 eGPU Hotplugging isn't working well on NUC8 (or most PC motherboards, except the Gigabyte x299 series). You may try to connect the eGPU before you boot up NUC. Also, your `ig-platform-id` should be changed to a headless one; or you could also inject key `framebuffer-portcount` with value `0` in the type of `number` under your `config/device/properties` (see snapshot). This is necessary to get full eGPU acceleration for FCP X, whereas not necessary for DaVinci Resolve.
![](https://i.imgur.com/S0aBO9b.jpg)

**Comment by sarkrui** [comment]
@BumpyClock I haven't had the time to test the latest version on my build, unfortunately. But if you want to downgrade, you could try removing the jumper on the motherboard and booting up NUC8 with F2 pressed.

**Comment by BumpyClock** [comment]
I tried downgrading. With the security jumper removed, I see the recovery menu press F4 and then the screen just goes blank and nothing happens. The USB Stick is formatted with FAT32 per instructions on Intel's site. I am still at BIOS 0081.

I am booting with the eGPU connected on boot. The box powers on, but the egPU is not detected. When I was on BIOS 56 a year ago and attempted the same build it would show up. It did not detect any thunderbolt devices but it would detect the graphics card.

**Comment by sarkrui** [comment]
You can probably follow the instruction. [BIOS Recovery by the Security Jumper](https://www.intel.com/content/www/us/en/support/articles/000005532/mini-pcs.html) It worked for me but you just need some patience and more tries; There're SSDTs on tonymacx86 (https://www.tonymacx86.com/threads/in-progress-ssdt-for-thunderbolt-3-hotplug.248784/) that can inject tb3 devices but it neither improves the performance nor supports tb3 hotplugging.
