### ISSUE TITLE
Apple TV+ black Screen on iGPU

### ISSUE THREAD

**Issue by thiroxx** [sarkrui/NUC8i7BEH#22]
I only get black screens on my NUC8i3 with internal GPU. In Safari Prime fails. So it seems there's something wrong with DRM. Any Advice?

**Comment by sarkrui** [comment]
As far as l know, without a dGPU it doesn't seem possible to play DRM contents. For more information, please check [DRM Compatibility Chart for 10.15
](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Chart.md)
