### ISSUE TITLE
Choosing Wi-Fi/BT card for NUC8

### ISSUE THREAD

**Issue by ithakaa** [sarkrui/NUC8i7BEH#25]
_BCM94360CS2 (2 antenna IPEX4 connector) Wi-Fi/Bluetooth + M.2 NGFF Key B+M Adapter. Intel antenna replacement is NOT required but 2.4 GHz will have conflicts with bluetooth as they share the same connector._

What does this mean ?
Do we need to remove the internal cables from the soldered WiFI/BT card ?

**Comment by sarkrui** [comment]
Hi @ithakaa,
Sorry about the confusion. The built-in Intel WiFi/BT doesn't support as well as a genuine Apple card, even if there's a [project](https://github.com/OpenIntelWireless/itlwm), allowing you to use Intel BT/WiFi on Mac. 

I prefer to use an Apple card for better usability. However, NUC8 uses an IPEX1 connector. So you can either buy a BCM94360CS2 card and use the original antenna, or buy a BCM94360CD with built-in antenna replaced. 
![Untitled-1](https://user-images.githubusercontent.com/14228455/96074931-37e64880-0eaa-11eb-966e-ac08a34cd55b.jpg). If you only have two antenna, you will then need to share 2.4GHz port for both Bluetooth and Wi-Fi/2.4Ghz 

I hope the image can clarify a bit. (see the size and the number of connectors)

**Comment by ithakaa** [comment]
HI 

I have the BCM94360CS2 installed and WiFi is working without issue, it's fantastic

I've installed my own antenna to the two ports on the BCM94360CS2 so am wondering if I need to disconnect the two antenna from the soldered on board ?

I definitely have disabled the onboard WiFI/BT so this is my confusion

**Comment by sarkrui** [comment]
> I definitely have disabled the onboard WiFI/BT so this is my confusion

If you have disabled the onboard Wi-Fi/BT, then it should be alright. No conflicts. But I wonder why you need to install extra antenna. BCM94360CS2 should be able to use the Intel antenna.

**Comment by ithakaa** [comment]
> But I wonder why you need to install extra antenna. BCM94360CS2 should be able to use the Intel antenna.

yes, well, thats a good question, I will use the internal antenna and see what happens
