### ISSUE TITLE
Kexts for Apple WLAN/Bluetooth/Airdrop

### ISSUE THREAD

**Issue by xDsquare** [sarkrui/NUC8i7BEH#3]
Thank you for this great project.
What are the kexts required for Apple Wifi and Bluetooth? 
(I want to use it on an already finished build)

**Comment by sarkrui** [comment]
If you are using BCM94360XXX cards, they work OOB, no KEXTs modification required;
If you are using BCM94330 series, they only work on certain SMBIOS models.
And of course, you need an adapter to convert Apple 12+6 pins to M.2 NGFF Key B+M.

**Comment by xDsquare** [comment]
Thank you very much for the fast answer.
I ordered "BCM943602CDP" and the adapter. 
It will work without any KEXTs?

**Comment by sarkrui** [comment]
Yep, that's exactly the card I am using right now for my NUC8. Also, keep that mind, that you also need to connect the data pin from the adapter to the internal USB. 
![](https://camo.githubusercontent.com/cc87f2868cc987e8dc22875e4b232504c3119002/68747470733a2f2f692e696d6775722e636f6d2f6e71526c7765422e706e67)

**Comment by xDsquare** [comment]
Alright, thank you :)

**Comment by xDsquare** [comment]
Hey, the adapter in your scheme looks like this (1) but only devices, which look like this (2) fit into the NUC8i7BEH. What did I missed?

![1](https://user-images.githubusercontent.com/24924023/60436061-83b8a400-9c0b-11e9-907d-86599e262272.png)
![2](https://user-images.githubusercontent.com/24924023/60436067-87e4c180-9c0b-11e9-8815-1f2c0b2b5697.png)

Thank you in advance.

**Comment by xDsquare** [comment]
Hey sarkrui, I build in the adapter with the chip today with the data pin connected to the internal USB port a shown in the scheme but when I boot and try to use Wifi/Bluetooth/Airdrop there is no function.
It's not finding any bluetooth devices or wifi networks. 
I'm booting with following kexts.:

![Screenshot 2019-07-01 at 16 29 14](https://user-images.githubusercontent.com/24924023/60444552-c1bec380-9c1d-11e9-99a8-a4fc7ea28be0.png)

Also, if I try to boot with the kexts below additionally it makes now difference.:
- AirportBrcmFixup.kext
- BrcmFirmwareRepo.kext
- BrcmPatchRAM2.kext

![Screenshot 2019-07-01 at 16 35 23](https://user-images.githubusercontent.com/24924023/60444837-44478300-9c1e-11e9-8054-2381f5116710.png)

Is it possibly a hardware issue?
Thanks in advance.
