### ISSUE TITLE
 The effect of using a SATA slo

### ISSUE THREAD

**Issue by ghost** [sarkrui/NUC8i7BEH#6]
I just want to know the effect of using a SATA slot.
Can you tell me the speed of SATA III SSD?

**Comment by sarkrui** [comment]
The SATA III port can theoretically support up to 6Gpbs (600MB/s, data transfer rate value by 1000 on macOS). I can practically reach ~540MB/s (reading) and 500MB/s (writing). If you're going to edit 4K@60fps videos (ProRes4444 or even Raw), using SATA III port is obviously not recommended.
