### ISSUE TITLE
Wake up on lan

### ISSUE THREAD

**Issue by Vincz** [sarkrui/NUC8i7BEH#8]
Hey guys!
So the setup is working really great. I put a Plex server on it. The problem is that when the NUC goes to sleep... there is no way to wake it up through LAN by accessing Plex. 
Is the BIOS configuration "Wake on LAN from S4/S5" absolutely mandatory ? 
Thanks!

**Comment by sarkrui** [comment]
@Vincz Not really, as suggested by **Rehabman**, “if you do not need if it, please disable it.” Please feel free to adapt the setup to your need.
